// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package pkg

import (
	"github.com/gofiber/fiber"
	"github.com/google/wire"
	"github.com/roger-king/gh-template/pkg/config"
	"github.com/roger-king/gh-template/pkg/handlers"
	"github.com/roger-king/gh-template/pkg/repositories"
)

// Injectors from server.go:

func New() (*fiber.App, error) {
	configConfig := config.NewConfig()
	statusRepository := repositories.NewStatusRepository(configConfig)
	statusHandler := handlers.NewStatusHandler(statusRepository)
	app := NewApp(statusHandler)
	return app, nil
}

// server.go:

var ServerSet = wire.NewSet(AppSet)
